### ISSUE TITLE
[Feature Request] Accents in scry previews

### ISSUE THREAD

**Issue by dreamsUnwind** [Nensec/FRTools#11]
i mean, it's in the title, isn't it? it'd be nice to be able to see the skins/accents in the outfit or be able to add them separately! obviously if this is too much of a bother it's not an issue at all it just means fifteen extra seconds of work on my end :p

**Comment by Nensec** [comment]
It is possible but it is a lot more work than it would seem like to automate.
The way how it combines the two images is to simply apply the invisibility cloak to the outfit of the dressing room and then slap the output on top of the scry image. The invisibility cloak hides the dragon, but that sadly includes the skin applied in the dressing room tool. So if I would want to add the skin to the scry dresser result I would have to:

1. Make a call to get the apparel image
2. Make a call to get just the skin image ( <- it is this part I have issues with )
3. Apply needed eye mask to the skin image (in case of multi/primal or glow)
4. Merge the edited skin image to the scry image
5. Merge the apparel image to the scry image

The reason I have an issue with doing that 2nd call is because I don't want to appear like I am harvesting skin files, nor do I want to cause a burden on the Flight Rising website by doubling my calls to them if I can avoid it.

I'll think about it, it is certainly possible and if it is a feature asked often I will likely add it anyway.
