### ISSUE TITLE
Unable to log in with Discord

### ISSUE THREAD

**Issue by Vaycol** [Nensec/FRTools#16]

**Comment by Nensec** [comment]
Apologies, this shouldn't have been live yet. This is working fine locally but it is missing something on live

**Comment by Iqyll** [comment]
For several months I've been having the exact same problem. I cannot log in with Discord, no matter how many times I try. I figured I'd ask here because it doesn't look like this will be fixed for me anytime soon.

**Comment by Nensec** [comment]
I have a fix, but it is currently part of the discord bot feature update (https://github.com/Nensec/FRTools/tree/disco_bot) that got stalled due to IRL commitments. This was meant to be pushed live a while ago. I'll see if I can maybe either finish that update or get the required code out of it to fix the login itself

**Comment by Nensec** [comment]
With the latest feature update, this should now be fixed. I'm sorry it took so long :x

**Comment by Iqyll** [comment]
It worked, thank you (:
