### ISSUE TITLE
Certain Scries don't seem to work & apparel is missing on 2nd dragon preview

### ISSUE THREAD

**Issue by MyshkaMoya** [Nensec/FRTools#18]
A preview using this scry link "https://www1.flightrising.com/dgen/preview/dragon?age=1&body=94&bodygene=21&breed=10&element=3&eyetype=1&gender=0&tert=75&tertgene=17&winggene=26&wings=75&auth=a238ccdfd51fd0d3fdcc0a04ba187fd8d3e2c815&dummyext=prev.png" shows up like this

![Image of preview](https://i.imgur.com/NDWoFuD.png)

Preview of dragon 58745847 comes out like this
![Image of preview2](https://i.imgur.com/UMaRw04.png)
even though the dragon is wearing apparel

**Comment by Nensec** [comment]
I'll have a look right away

**Comment by Nensec** [comment]
The apparel problem seemed to be a caching problem on the CDN part, for some reason. I purged the cache and it loads fine now. I don't really know what causes it to cache the wrong image, and it is not something in my control either as I rely on the Azure CDN framework. Looking at the source of the CDN the images were correct, but the output of the CDN was not.

The dummy image from the scry is a bit of a mystery still, since I saw it happening, in code as well, but then it magically fixed itself before I could debug it further. The skin seems to preview just fine now. If this happens again then please let me know so I can look into it again.

**Comment by MyshkaMoya** [comment]
Alright! Thank you
